// <auto-generated />
using System;
using BreweryWarehouse.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreweryWarehouse.Web.Migrations
{
    [DbContext(typeof(BreweryWarehouseDbContext))]
    [Migration("20260516194155_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BreweryWarehouse.Model.BeerStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlcoholPercentage")
                        .HasColumnType("float");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<double>("ColorEBC")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IBU")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BeerStyles");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BestBefore")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("SLCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Container");

                    b.HasDiscriminator().HasValue("Container");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanId")
                        .HasColumnType("int");

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KegId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanId");

                    b.HasIndex("ContainerId");

                    b.HasIndex("KegId");

                    b.HasIndex("LocationId");

                    b.ToTable("StockEntries");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.WarehouseLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aisle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Shelf")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WarehouseLocations");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Can", b =>
                {
                    b.HasBaseType("BreweryWarehouse.Model.Container");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BeerStyleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PackagingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasIndex("BeerStyleId");

                    b.HasDiscriminator().HasValue("Can");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Keg", b =>
                {
                    b.HasBaseType("BreweryWarehouse.Model.Container");

                    b.Property<int>("BeerStyleId")
                        .HasColumnType("int");

                    b.Property<int>("HeadType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastInspection")
                        .HasColumnType("datetime2");

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VolumeInLitres")
                        .HasColumnType("int");

                    b.HasIndex("BeerStyleId");

                    b.ToTable("Container", t =>
                        {
                            t.Property("BeerStyleId")
                                .HasColumnName("Keg_BeerStyleId");
                        });

                    b.HasDiscriminator().HasValue("Keg");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.StockEntry", b =>
                {
                    b.HasOne("BreweryWarehouse.Model.Can", null)
                        .WithMany("StockEntries")
                        .HasForeignKey("CanId");

                    b.HasOne("BreweryWarehouse.Model.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BreweryWarehouse.Model.Keg", null)
                        .WithMany("StockEntries")
                        .HasForeignKey("KegId");

                    b.HasOne("BreweryWarehouse.Model.WarehouseLocation", "Location")
                        .WithMany("StockEntries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Can", b =>
                {
                    b.HasOne("BreweryWarehouse.Model.BeerStyle", "BeerStyle")
                        .WithMany("Cans")
                        .HasForeignKey("BeerStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeerStyle");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Keg", b =>
                {
                    b.HasOne("BreweryWarehouse.Model.BeerStyle", "BeerStyle")
                        .WithMany("Kegs")
                        .HasForeignKey("BeerStyleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeerStyle");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.BeerStyle", b =>
                {
                    b.Navigation("Cans");

                    b.Navigation("Kegs");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.WarehouseLocation", b =>
                {
                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Can", b =>
                {
                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("BreweryWarehouse.Model.Keg", b =>
                {
                    b.Navigation("StockEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
